import React, { Component } from 'react';
import './TermsAndConditions.css';

export class TermsAndConditions extends Component {

    render() {
        return (
            <div id="div_terms_and_conditions">
                <span><b>General Terms of Service</b></span><br/>
                <span>Last updated: September 12, 2021</span><br /><br />

                <span>PLEASE READ THESE TERMS OF SERVICE CAREFULLY. AMONG OTHER THINGS, THEY PROVIDE KEY INFORMATION ON YOUR LEGAL RIGHTS AND OBLIGATIONS, FUTURE CHANGES TO THE TERMS, AUTOMATIC RENEWALS AND LIMITATIONS OF LIABILITY. THESE TERMS ALSO CONTAIN A MANDATORY CLASS ACTION WAIVER IN SECTION 12 WHICH AFFECTS HOW DISPUTES ARE RESOLVED.</span><br /><br />

                <span>These General Terms of Service (“General Terms”), along with any applicable Additional Terms (see section 1 below) (collectively, the “Terms”) govern your use of and access to our websites, customer support, any interactive areas, software, applications and other services (collectively, the “Services”).</span><br /><br />

                <span>The Services are provided by the entity specified in Section 14 of these General Terms (“we,” “us,” “our,” or “Safe Accounts”). Please note that the Terms constitute a binding legal agreement between you and Safe Accounts. By visiting our websites, installing, and/or using the Services, you acknowledge that you have read the Terms, understand them, and agree to be bound by these Terms. If you are using the Services on behalf of an organization, you are agreeing to these Terms for that organization and acknowledging that you have the authority to act on behalf of that organization and commit to these Terms on behalf of that organization. If you do not agree with these Terms or any provisions hereof, please do not install and do not use our Services.</span><br /><br />

                <span><b>1. Your Agreement with Safe Accounts</b></span><br />
                <span>Additional Terms. Our Services are subject to one or more of the additional terms below (“Additional Terms”). If there is any conflict between the terms in the General Terms and the Additional Terms, then the Additional Terms govern in relation to that Service.</span><br /><br />

                <span>Updates to Terms. Safe Accounts may modify the Terms from time to time. The most recent version is the version that applies to your use of the Services. If the changes include material changes that affect your rights or obligations, we will notify you in advance of the changes by reasonable means, which could include notification through the client applications, website or via email. Unless it is stated by us otherwise, each update of the Terms comes into force as of the moment when amended Terms are published on this web page. You understand and agree that any continued use and access to the Services after any updates to these Terms are published, means that you voluntarily agree to be bound by the updated Terms.</span><br /><br />

                <span><b>2. Our Services</b></span><br />
                <span>To use any of our Services, you must set up an account. You are solely responsible for all usage or activity on your account including, but not limited to, use of the account by any person who uses your account, with or without authorization, or who has access to any computer on which your account resides or is accessible.</span><br /><br />

                <span>You are responsible for maintaining the confidentiality of your Safe Accounts account username and password and for restricting access to your account. You may not share your password or other account access information with any other party, temporarily or permanently, and you agree to accept responsibility for all activities that occur under your account or password, whether or not authorized by you. You agree to immediately notify us of any unauthorized use of your account, username or password, as the case may be.</span><br /><br />

                <span>Your use of the Services is at your own risk. The Services may be modified, updated, interrupted or suspended at any time without notice or liability. We do not bear any liability for any harm or other adverse consequences to you, caused by this. Safe Accounts, its owners, employees, agents and others that are involved with the Services are not in any way or form liable for any harm of any kind executed or intended, resulting from or arising through or from the use of any account registered with Services.</span><br /><br />

                <span><b>3. License conditions</b></span><br />
                <span>Subject to the terms and conditions of these Terms, we grant you a limited, revocable, non-exclusive, personal, non-transferable, non-sublicensable, fixed-term license to: (1) download and use a copy of our software; and (2) use the Services, including, without limitation, the products and services made available on or through the our software or our website. No other right or license, express or implied, of any kind is granted to you hereunder with respect to the Services. The license provided herein is effective until terminated. This license automatically terminates if you fail to comply with these Terms.</span><br /><br />

                <span>The Services, including, but not limited to, our software, mobile application and all other products, are owned and copyrighted by Safe Accounts and protected worldwide. We retain all right, title and interest in and to the Services and any portion thereof, including, without limitation, all copyrights, trademarks, service marks, patents, trade secrets and other intellectual property rights. You shall not take any action to jeopardize, limit or interfere in any manner with our ownership of and rights with respect to the Services. All rights are reserved unless otherwise noted.</span><br /><br />

                <span>By accessing and using this website and by using the Services, you accept and acknowledge that the Services, including the appearance, content, selection, assembly and functionality and any other parts or specifics of our websites and the Services, is the ownership of Safe Accounts (despite whether the specific content is individually protected by copyright). Safe Accounts is a protected trademark and you are forbidden from registration, adoption or any other use of trade names, symbols or signs that are either identical or confusingly similar to any trademarks owned by Safe Accounts.</span><br /><br />

                <span>The version of the Services and software available at your renewal date may be different from the version available when you first purchased your license from us. We provide application updates for all OS versions for at least two years after the initial OS version release.</span><br /><br />

                <span><b>4. Payments</b></span><br />
                <span>All our paid Services are subscribed on a service period basis. You choose the service period and the payment method yourself when you sign up for the paid Services. Your service will automatically be renewed, and your chosen payment method will be charged at the end of each service period, unless you decide to cancel your automatic payments for the Services before the end of the then-current subscription. All prices, including recurring subscription fees, are subject to change. Any changes in pricing will be communicated to you in advance. If you update payment details in your account, the updated information will be regarded as your preferred method for any future payments.</span><br /><br />

                <span>In some cases, we or others on our behalf may offer a free trial for our paid Services. The duration of the free trial period and other details will be specified during a sign-up. We determine your free trial eligibility at our sole discretion, and to the extent permitted under applicable law we may limit or withdraw a free trial option at any time without prior notice. You acknowledge and agree that we will automatically charge you for our paid Services at the end of the free trial period on a recurring basis. If you do not want to be charged, you must cancel the paid subscription before the end of the free trial by contacting our support team. If you received a free trial from a third party, you may also cancel the paid subscription through that third party.</span><br /><br />

                <span>Only basic payment information is processed through our payment service providers and payment processing partners authorized to provide services within respective country.</span>

                <span>Any fees charged by us are exclusive of taxes. However, we may calculate and add any taxes and / or additional fees, including, but not limited to sales tax, value added tax and other taxes or fees under laws applicable to you. Such taxes and fees will be calculated according to the billing information provided by you to Safe Accounts at the time of purchase.</span>

                <span><b>5. Refund and cancellation policy</b></span>
                <span>If you wish to claim a refund, you can do so within 30 days following your purchase of our Services. We seek your full satisfaction with our Services. However, we would like to troubleshoot an issue you experience first. There are common service configuration issues that may hinder the Services for you, and we resolve most user issues encountered.</span><br /><br />

                <span>Subscriptions purchased via the iTunes/App Store are subject to iTunes/App Store refund policies. This means we cannot grant refunds if you purchased an app through iTunes/App Store – you will have to contact store support for that. Payments made using prepaid cards or gift cards will not be refunded. Safe Accounts cannot refund any purchases made from our resellers (Amazon, BestBuy, StackSocial, etc.). In this case, refunds are handled according to the terms of service of the reseller from which the product was purchased. For payments made in cryptocurrency, the equivalent amount in US Dollars will be refunded in the same cryptocurrency (based on the rate of exchange at the moment of refund).</span><br /><br />

                <span>You have a right to cancel your account at any time. You can cancel a recurring subscription from your Safe Accounts account, iTunes/App Store or Google Play Store. Canceled accounts will not be refunded for the unused part of the ongoing service period.</span><br /><br />

                <span>You can only get a refund for our Services twice. If you buy any of our Services again after that, you will not be granted a refund for any further cancellation. We do not grant refunds for recurring subscription payments if you cancel the Services after the renewal, unless applicable law provides otherwise. No refunds will be considered for accounts terminated for violation of these Terms. Once the refund is issued to you, you will lose access to the Services.</span><br /><br />

                <span><b>6. Minors</b></span><br />
                <span>The Services are not directed to minors, and any use by minors should only be done with the guidance, supervision and consent of their parents or guardians. Further, we rely on parents and guardians to ensure minors only use the Services if they can understand their rights and responsibilities as stated in these Terms and Conditions.</span>

                <span>Consistent with applicable law, Safe Accounts does not knowingly collect personal information from minors without parental consent. If we learn that we have inadvertently obtained information in violation of applicable laws prohibiting collection of information from children without such consent, we will promptly delete it.</span>

                <span><b>7. Prohibited and restricted uses</b></span>
                <span>Your access to and use of the Services is subject to these Terms and all applicable laws and regulations. We reserve the right, at any time, in our sole discretion, with or without notice, to terminate the accounts of, and block access to the Services to any users who infringe any applicable laws or these Terms.</span>

                <span>You agree that you shall not:</span><br /><br />

                <span>use, assist, encourage, or enable others to use the Services for any unlawful, illicit, illegal, criminal or fraudulent activities, including but not limited to port scanning, sending spam, sending opt-in email, scanning for open relays or open proxies, sending unsolicited email or any version or type of email sent in vast quantities even if the email is routed through third-party servers, any pop-up launching, use of stolen credit cards, credit card fraud, financial fraud, cryptocurrency fraud, cloaking, extortion, blackmail, kidnapping, rape, murder, sale of stolen credit cards, sale of stolen goods, offer or sale of prohibited and dual-use goods, offer or sale of controlled substances, identity theft, hacking, pharming, phishing, scraping in any form or scale, digital piracy and other similar activities;</span><br />
                <span>assault, interfere, gain unauthorized access, deny service in any way or form to any other network, computer or node through our Services;</span><br/>
                <span>exploit children in any way, including audio, video, photography, digital content, etc.;</span ><br />
                <span>violate, infringe, or misappropriate other people's intellectual property, privacy or other legal rights;</span><br />
                <span>share anything that is illegal, abusive, harassing, or otherwise objectionable;</span><br />
                <span>transmit any viruses or other computer instructions or technological means that disrupt, damage, or interfere with the use of computers or related systems;</span><br />
                <span>attempt to circumvent any technological measure implemented by Safe Accounts;</span><br />
                <span>interfere with or disrupt the integrity or performance of the Service;</span><br />
                <span>take any action that imposes or may impose an unreasonable or disproportionately large load on our infrastructure;</span><br />
                <span>sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Services in any way;</span><br />
                <span>use any robot, spider, scraper, or other automated means to access our website or Services for any purpose without our prior written permission;</span><br />
                <span>build a product using similar ideas, features, functions or graphics of the Service or copy any ideas, features, functions or graphics of the Services;</span><br />
                <span>claim that you are the representative or agent of any of the Services, including any of its functionality;</span><br />
                <span>threaten, stalk, harm, or harass others, or promote bigotry or discrimination;</span><br/>
                <span>attempt to gain unauthorized access to the Services, user accounts, computer systems or networks connected to the Services through hacking, password mining, brute force or any other means;</span><br />
                <span>violate general ethic or moral norms, good customs and fair conduct norms;</span><br />
                <span>use the Services for anything other than lawful purposes;</span><br />
                <span>to use the Services for any military purpose, including cyber warfare, weapons development, design, manufacture or production of missiles, nuclear, chemical or biological weapons;</span><br />
                <span>to otherwise infringe or circumvent these Terms.</span><br />
                <span>We reserve the right to refuse service, suspend accounts or limit access to the Services in our sole discretion. Such suspension or access limitation may be implemented by Safe Accounts instantly and without any indication, notice or refund. We may suspend your account for clarification, investigation or request you to explain your actions and provide additional information. If your account has been suspended, you must contact us for further information. We may suspend your user account for a reasonable period of time before we terminate a user account permanently.</span><br /><br />

                <span>We use automated tools to identify web scraping and minimize the service abuse. These tools are looking for irregular patterns when new sessions are initiated and if such patterns are noticed, it might automatically suspend your account or otherwise limit your access to the Services until further investigation is complete.</span><br /><br />

                <span>You access and use the Services in your country on your own initiative, and you solely are responsible for complying with your local laws and regulations if and to the extent such laws are applicable. We reserve the right to limit, in our sole discretion, the availability of the Services or any portion thereof, to any person, entity, geographic area, or jurisdiction, at any time.</span><br /><br />

                <span>You are disallowed to connect and use the Services if you are a minor, a competitor of our business, if you have been or are prohibited to access the Services, or if your account has been suspended or closed due to any reason.</span><br /><br />

                <span>We encourage you to let us know about the violation of these Terms by any of Safe Accounts users; in case of such violations, we may take appropriate action at our sole discretion.</span><br /><br />

                <span><b>8. Disclaimer of warranties</b></span>
                <span>Reasonable efforts are taken to improve the accuracy and integrity of the Services, but complex software is never wholly free from defects, errors and bugs. We give no warranty or representation that the Services will be wholly free from defects, errors and bugs, such as downtime, loss of data, corrupt data, service delay, mistakes, out-of-date information, or other. Notwithstanding any other provision of these Terms, we reserve the right to change, suspend, remove, or disable access to the Services, or any functionality comprising a part of the Services at any time without notice. In no event will we be liable for making these changes. We do not warrant and will not have any liability or responsibility for your use of the Services or other products or services we provide. We may also impose limits on the use of or access to the Services, for any reason and without notice or liability. Our Services may be unavailable from time to time due to human, digital, mechanical, telecommunication, software, and other failures. We cannot predict or control when such downtime may occur and cannot control the duration of such downtime.</span><br /><br />

                <span>THE SERVICES (INCLUDING, WITHOUT LIMITATION, OUR SOFTWARE, MOBILE APPLICATIONS, SERVICES AND WEBSITE) ARE PROVIDED “AS IS” AND WITH ALL FAULTS. WE MAKE NO REPRESENTATION OR WARRANTY WHATSOEVER REGARDING THE COMPLETENESS, ACCURACY, ADEQUACY, SUITABILITY, FUNCTIONALITY, AVAILABILITY, OR OPERATION OF THE SERVICES. YOU ACKNOWLEDGE THAT WE DO NOT HAVE CONTROL OVER YOUR USE OF THE SERVICES, AND WE DO NOT WARRANT THE PERFORMANCE OR RESULTS THAT MAY BE OBTAINED THROUGH YOUR USE OF THE SERVICES. YOU ASSUME ALL RISKS AND RESPONSIBILITY FOR YOUR USE OF THE SERVICES AND FOR ANY LOSS OF OR ERRORS IN ANY DATA OR INFORMATION. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING THROUGH COURSE OF DEALING OR USAGE OF TRADE. WITHOUT LIMITING THE FOREGOING, WE NEITHER WARRANT NOR REPRESENT THAT YOUR USE OF THE SERVICES WILL NOT INFRINGE THE RIGHTS OF ANY THIRD PARTIES, NOR THAT THE SERVICES WILL BE AVAILABLE FOR YOUR ACCESS OR USE, NOR THAT OPERATION OF THE SERVICES WILL BE ERROR-FREE OR UNINTERRUPTED. PLEASE NOTE THAT SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. IN ADDITION, YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM ONE JURISDICTION TO ANOTHER JURISDICTION.</span><br /><br />

                <span>We shall not be responsible or have any liability for any delay or failure to perform to the extent due to unforeseen circumstances or causes beyond our reasonable control, including, without limitation, failures of third party software (whether open or not), failures of your telecommunication or internet service providers, force majeure, earthquakes, fires, floods, embargoes, labor disputes and strikes, riots, war, novelty of product manufacture or other unanticipated product development problems, and acts of civil and military authorities.</span><br /><br />

                <span><b>9. Limitation of liability</b></span><br />
                <span>There are inherent risks in relying upon, using, transmitting, or retrieving any data and/or content on the Internet, and we urge you to make sure you understand these risks before using the Services.</span><br /><br />

                <span>YOUR USE OF THE SERVICES IS AT YOUR OWN RISK. NEITHER Safe Accounts NOR ANY OF ITS PARENTS, SUBSIDIARIES OR AFFILIATES, NOR ANY OF THEIR EMPLOYEES, OFFICERS OR DIRECTORS, SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR OTHER DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF DATA OR INFORMATION OF ANY KIND, LOSS OF BUSINESS, LOST PROFITS, INTERRUPTION OF BUSINESS, COST OF COVER OR ANY OTHER DAMAGES) ARISING OUT OF OR IN ANY WAY RELATED TO THIS AGREEMENT OR THE USE OR INABILITY TO USE THE SERVICES, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN ANY CASE, THE LIABILITY OF Safe Accounts SHALL NOT EXCEED WHAT THE CLIENT PAID TO Safe Accounts AND SHALL NOT INCLUDE ATTORNEY FEES OR COURT COSTS IRRESPECTIVE OF ANY LAWS OR STATUTES THAT MAY PRESCRIBE OTHERWISE.</span><br /><br />

                <span><b>10. Indemnification</b></span><br />
                <span>You agree, at your own expense, to indemnify, defend and hold harmless Safe Accounts, its parents, subsidiaries and affiliates, and their officers, directors, employees, agents, distributors and licensees, from and against any judgments, losses, deficiencies, damages, liabilities, costs, claims, demands, suits, and expenses (including, without limitation, reasonable attorneys’ fees, expert witness fees and expenses) incurred in, arising out of or in any way related to your breach of these Terms, your use of the Services, or any of your other acts or omissions.</span><br /><br />

                <span><b>11. Electronic communications</b></span><br />
                <span>You agree to receive communications from us electronically, e.g., by email, application messages, etc. and consent that such notifications satisfy any legal requirement for communication in writing. You agree that we may communicate to you for the purpose of advising you of changes or additions to the Services, about any of our products or services, or for such other purposes that are reasonable or required by applicable law.</span><br /><br />

                <span>When communicating with our customer support representatives, you agree to be respectful and kind. If we feel that your behavior towards any of our customer support representatives or other employees is at any time threatening or offensive, we reserve the right to immediately terminate your account.</span><br /><br />

                <span><b>12. Class action waiver</b></span><br />
                <span>Where permitted under the applicable law, class action lawsuits, class-wide arbitrations, private attorney-general actions, and any other proceeding where someone acts in a representative capacity are not allowed. Unless both you and Safe Accounts agree, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative or class proceeding.</span><br /><br />

                <span><b>13. Application Platform Terms</b></span><br />
                <span>If our application is downloaded from Apple, Inc. (“Apple”) App Store or if you are using the Services on an iOS device, you acknowledge that you have read, understood, and agree to the following notice regarding Apple.</span><br /><br />

                <span>These Terms are concluded between you and Safe Accounts, not with Apple, and Apple is not responsible for the Services and the content thereof. Apple has no obligation whatsoever to furnish any maintenance or support services for the Service To the extent that the Services fails to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the Service to you; to the maximum extent permitted by law, Apple will have no other warranty obligation with respect to the Services. Apple is not responsible for addressing any claims by you or any third party relating to the Service or your possession and/or use of the Service, including: (1) product liability claims; (2) any claim that the Service fails to conform to any applicable legal or regulatory requirement; and (3) claims arising under consumer protection or similar legislation. Apple is not responsible for the investigation, defense, settlement, and discharge of any third-party claim that the Service and/or your possession and use of the application infringe that third party’s intellectual property rights. You agree to comply with any applicable third-party terms, when using the Service. Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms, and upon your acceptance of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary of these Terms. You hereby represent and warrant that (1) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (2) you are not listed on any U.S. Government list of prohibited or restricted parties.</span><br /><br />

                <span><b>14. Miscellaneous</b></span><br />
                <span>We reserve the right to modify and update these Terms at our sole discretion, at any time, for any reason, and without liability.</span><br /><br />

                <span>We also reserve the right to modify or update the operation of the Services at our sole discretion, at any time, for any reason, and without notice or liability. We may even suspend the Services entirely, in which event we will notify you in advance unless extenuating circumstances, such as safety or security concerns, prevent us from doing so.</span><br /><br />

                <span>The Terms constitute an agreement between you and us regarding the use of the Services. The parties acknowledge that no reliance is placed on any representation made but not expressly contained in these Terms.</span><br /><br />

                <span>If any provision of the Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that the Terms shall otherwise remain in full force and effect and enforceable.</span><br /><br />

                <span>You may not assign these Terms or any rights or interest under these Terms or delegate any obligations to be performed under these Terms, without the Safe Accounts’s prior written consent. Safe Accounts can assign its rights and obligations under these Terms to selected third parties without your consent, including but not limited to, in cases of corporate reorganization, merger, acquisitions, sale or transfer of all or substantially all of company assets.</span><br /><br />

                <span>For all purposes, the English language version of the Terms shall be the original, governing instrument and understanding between you and us. In the event of any conflict between this English language version of the Terms and any subsequent translation into any other language, the English language version shall govern and control.</span>
            </div>
        );
    }
}
